apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: apache-php
  sources:
    - repoURL: https://github.com/azarkawi/wordpress
      path: wordpress
      targetRevision: file-structure
