apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-backup-pv
  namespace: apache-php
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mariadb-backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pvc
  namespace: apache-php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
